### ISSUE TITLE
'./data/train-terms-processed.json' not found

### ISSUE THREAD

**Issue by sylxjtu** [nijianmo/arc-etrr-code#1]
Hi, thanks for publishing the code!

After cloning this project, I downloaded the `/data` content from the google drive link in the README, ran `python preprocess.py conceptnet`, and got following error log.

```
preprocess conceptnet...
load arc data...
1119it [00:19, 56.23it/s]
299it [00:05, 55.93it/s]
1172it [00:21, 54.55it/s]
load selector data...
Traceback (most recent call last):
  File "preprocess.py", line 435, in <module>
    preprocess_conceptnet(os.path.join(concept_path, 'conceptnet-assertions-5.6.0.csv'))
  File "preprocess.py", line 403, in preprocess_conceptnet
    build_vocab_from_raw_dataset()
  File "preprocess.py", line 371, in build_vocab_from_raw_dataset
    with jsonlines.open(data_path) as reader:
  File "C:\Users\Dell\Anaconda3\lib\site-packages\jsonlines\jsonlines.py", line 328, in open
    fp = io.open(name, mode=mode + 't', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: './data\\train-terms.jsonl'
```

Then I ran `python .\retriever\selector\main.py --epoch 100 --embedding_file C:\Users\Dell\Desktop\keyword\arc-etrr-code\data\glove\glove.840B.300d.txt`, then I got the following error.

```
Namespace(batch_size=32, dataset='Challenge', doc_layers=1, dropout_emb=0.5, dropout_rnn_output=0.5, elmo_num_layer=1, embedding_file='C:\\Users\\Dell\\Desktop\\keyword\\arc-etrr-code\\data\\glove\\glove.840B.300d.txt', epoch=100, finetune_topk=10, gpu='0', grad_clipping=10.0, hidden_size=96, lr=0.002, ner_emb_dim=8, optimizer='adamax', pos_emb_dim=12, pos_weight=2.5, pretrain_dataset='', pretrained='', rel_emb_dim=10, rnn_padding=True, rnn_type='lstm', seed=1234, test_mode=False, use_cuda=True, use_elmo=False, use_science_term=False, weight_decay=0)
Load vocabulary from ./data/vocab...
Vocabulary size: 36548
Load pos vocabulary from ./data/pos_vocab...
POS vocabulary size: 51
Load ner vocabulary from ./data/ner_vocab...
NER vocabulary size: 20
Load relation vocabulary from ./data/rel_vocab...
Rel vocabulary size: 40
Use cuda: False
WARNING:root:WARN: Duplicate embedding found for ;
simpleModel(
  (embedding): Embedding(36548, 300, padding_idx=0)
  (pos_embedding): Embedding(51, 12, padding_idx=0)
  (ner_embedding): Embedding(20, 8, padding_idx=0)
  (rel_embedding): Embedding(40, 10, padding_idx=0)
  (q_c_emb_match): SeqAttnMatch(
    (linear): Linear(in_features=300, out_features=300, bias=True)
  )
  (question_rnn): StackedBRNN(
    (rnns): ModuleList(
      (0): LSTM(610, 96, bidirectional=True)
    )
  )
  (project): Linear(in_features=225, out_features=1, bias=True)
)
Number of parameters:  638442
C:\Users\Dell\Anaconda3\lib\site-packages\torch\nn\_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File ".\retriever\selector\main.py", line 22, in <module>
    train_data = load_data('./data/train-terms-processed.json', model.elmo)
  File "C:\Users\Dell\Desktop\keyword\arc-etrr-code\retriever\selector\utils.py", line 40, in load_data
    for line in open(path, 'r', encoding='utf-8'):
FileNotFoundError: [Errno 2] No such file or directory: './data/train-terms-processed.json'
```

Thanks for your help!

**Comment by nijianmo** [comment]
Hi, sorry for the late response! I have uploaded these missing files to the /data folder on Google Drive. Hope this will help you fix the problem.

**Comment by sylxjtu** [comment]
Thanks for your help!
